### ISSUE TITLE
Design Sync: Link

### ISSUE THREAD

**Issue by scurker** [dequelabs/cauldron#1672]
The following changes need to be made to the `.Link` styles:

- remove `font-weight` 
- remove all `p .Link` styles
- remove `display: inline-block`

For links that include leading or trailing icons:

```css
.Link:has(.Icon) {
  display: inline-flex;
  align-items: center;
  gap: var(--space-half);
  flex-wrap: wrap;
}
```

And remove from `a` styles from `base.css`:

- `font-weight`

Link typography should generally be inheriting styles from css cascading.

The end result should be: All components that appear visually as Links should have a font-weight of 400.
