### ISSUE TITLE
Color contrast issue with syntax highlighting in light mode

### ISSUE THREAD

**Issue by scurker** [dequelabs/cauldron#369]
We need to ensure that we have proper color contrast for any syntax highlighting, we've had to temporarily implement some overrides in the axe extension:

```css
.cauldron--theme-light .Code .hljs-attr {
  color: var(--accent-error-active);
}

.cauldron--theme-light .Code .hljs-number,
.cauldron--theme-light .Code .hljs-selector-attr,
.cauldron--theme-light .Code .hljs-selector-pseudo {
  color: #bd1a38;
}

.cauldron--theme-light .Code .hljs-template-variable,
.cauldron--theme-light .Code .hljs-selector-id,
.cauldron--theme-light .Code .hljs-class .hljs-title {
  color: #6601a4;
}
```
