### ISSUE TITLE
Add indeterminate support to `<Checkbox />`

### ISSUE THREAD

**Issue by schne324** [dequelabs/cauldron#479]
The indeterminate state is the state of a checkbox where the checked value of the checkbox cannot be determined.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox#attr-indeterminate

## Design Specs

<details>
  <summary>Note: The designs originated from UXPin and the links are no longer accessible but the concepts are still applicable. Please note the proposed design does not match the current size of checkboxes and this is intentional.</summary>

### Dark mode
![image](https://github.com/dequelabs/cauldron/assets/28606186/da93ec65-98da-45b3-86c7-ae92e64ea4e4)

### Light mode
![image](https://github.com/dequelabs/cauldron/assets/28606186/1e939ea6-b9d7-4460-9ced-d80d1f9f4e5a)

</details>

No new icons are needed for this checkbox, the indeterminate state can be rendered purely with CSS, approximate styles below:

```css
.Checkbox input[type='checkbox']:indeterminate ~ .Checkbox__overlay:before {
  content: "";
  display: block;
  position: absolute;
  height: calc(var(--icon-size) - 8px);
  width: calc(var(--icon-size) - 8px);
  background: currentColor;
  transform: translate(4px, 4px);
}

.Checkbox input[type='checkbox']:indeterminate ~ .Checkbox__overlay:after {
  content: "";
  display: block;
  position: absolute;
  height: 3px;
  width: calc(var(--icon-size) / 2);
  background-color: var(--workspace-background-color);
  transform: translate(6px, calc(var(--icon-size) / 2 * -1 - 1.5px));
}
```

## Technical Details

For more context, this [github comment thread for react](https://github.com/facebook/react/issues/1798) provides specific details about implementation challenges with indeterminate checkboxes. The HTML spec does not allow for indeterminate properties to be set via an attribute, so it must be set via javascript.

The `checked` and `indeterminate` properties are incompatible, so we need to define the default behavior of what happens to the checkbox when it becomes `indeterminate` in either its checked or unchecked state.
