### ISSUE TITLE
Allow buttons to be inline or stacked depending on the screen size

### ISSUE THREAD

**Issue by anastasialanz** [dequelabs/cauldron#811]
https://deque.slack.com/archives/C5MUFQ7UM/p1665776153371979

**Comment by scurker** [comment]
My recommendation here is that we take a hybrid approach.

To address the immediate concern with buttons, we should use `:has` to progressively style the first element that is followed by a button as opposed to using the adjacent selector:

```css
[class*='Button--'] + [class*='Button--'] {
  margin-left: var(--space-smallest);
}

@supports selector(:has(*)) {
  [class*='Button--'] + [class*='Button--'] {
    margin-left: initial;
  }

  [class*='Button--']:has(+ [class*='Button--']) {
    margin-right: var(--space-smallest);
  }
}
```

This would work everywhere aside from Firefox, which currently [has not shipped support of `:has` as of May 2023](https://caniuse.com/css-has).

I'm in favor of adding some utility that would allow for some kind of flexible rendering/layout of children but not sure it needs to be scoped specifically to buttons and may have utility elsewhere. We can handle that on a separate ticket when we want to address that enhancement.
